-- Alcohol Label Verification - supporting database objects
-- Target application: Oracle APEX Application 102
--
-- Creates the ALV_* tables, ALV_BATCH_SUMMARY_V, seed configuration,
-- deterministic scenario data, and ALV_VERIFICATION_PKG.
--
-- Run from Oracle APEX: SQL Workshop -> SQL Scripts.
-- Do not paste this multi-statement script into SQL Commands.
--
-- WARNING: This is a destructive clean installer. It drops and recreates
-- the ALV_* objects and deletes existing ALV prototype data.

begin
  execute immediate 'drop package alv_verification_pkg';
exception
  when others then
    if sqlcode != -4043 then raise; end if;
end;
/

begin
  execute immediate 'drop view alv_batch_summary_v';
exception
  when others then
    if sqlcode != -942 then raise; end if;
end;
/

begin
  execute immediate 'drop table alv_verification_fields cascade constraints purge';
exception
  when others then
    if sqlcode != -942 then raise; end if;
end;
/

begin
  execute immediate 'drop table alv_verifications cascade constraints purge';
exception
  when others then
    if sqlcode != -942 then raise; end if;
end;
/

begin
  execute immediate 'drop table alv_batches cascade constraints purge';
exception
  when others then
    if sqlcode != -942 then raise; end if;
end;
/

begin
  execute immediate 'drop table alv_config cascade constraints purge';
exception
  when others then
    if sqlcode != -942 then raise; end if;
end;
/

create table alv_config (
  config_key    varchar2(100)  not null,
  config_value  varchar2(4000),
  description   varchar2(4000),
  updated_at    timestamp with local time zone default systimestamp not null,
  updated_by    varchar2(255),
  constraint alv_config_pk primary key (config_key)
);

create table alv_batches (
  id                  number generated by default on null as identity,
  public_token        varchar2(64) not null,
  manifest_file_name  varchar2(1000),
  zip_file_name       varchar2(1000),
  processing_mode     varchar2(30) not null,
  status              varchar2(20) default 'PROCESSING' not null,
  total_count         number default 0 not null,
  processed_count     number default 0 not null,
  pass_count          number default 0 not null,
  fail_count          number default 0 not null,
  review_count        number default 0 not null,
  processing_ms       number,
  notes               varchar2(4000),
  started_at          timestamp with local time zone default systimestamp not null,
  completed_at        timestamp with local time zone,
  created_by          varchar2(255),
  constraint alv_batches_pk primary key (id),
  constraint alv_batches_token_uq unique (public_token),
  constraint alv_batches_status_ck check (status in ('PROCESSING','COMPLETED','FAILED'))
);

create table alv_verifications (
  id                              number generated by default on null as identity,
  public_token                    varchar2(64) not null,
  batch_id                        number,
  application_ref                 varchar2(200) not null,
  file_name                       varchar2(1000),
  mime_type                       varchar2(255),
  image_blob                      blob,
  expected_brand_name             varchar2(500),
  expected_class_type             varchar2(1000),
  expected_abv                    number(8,3),
  expected_net_contents           varchar2(200),
  expected_producer               varchar2(1000),
  expected_country                varchar2(500),
  extracted_brand_name            varchar2(500),
  extracted_class_type            varchar2(1000),
  extracted_abv                   number(8,3),
  extracted_net_contents          varchar2(200),
  extracted_producer              varchar2(1000),
  extracted_country               varchar2(500),
  extracted_warning               varchar2(4000),
  warning_heading_all_caps        char(1),
  warning_heading_bold            char(1),
  extracted_text                  clob,
  provider_response               clob,
  provider                        varchar2(30) not null,
  demo_profile                    varchar2(30),
  overall_status                  varchar2(20) default 'PROCESSING' not null,
  confidence                      number(5,4),
  processing_ms                   number,
  http_status                     number,
  error_message                   varchar2(4000),
  created_at                      timestamp with local time zone default systimestamp not null,
  created_by                      varchar2(255),
  constraint alv_verifications_pk primary key (id),
  constraint alv_verifications_token_uq unique (public_token),
  constraint alv_verifications_batch_fk foreign key (batch_id)
    references alv_batches (id) on delete cascade,
  constraint alv_verifications_status_ck check
    (overall_status in ('PROCESSING','PASS','FAIL','REVIEW')),
  constraint alv_verifications_caps_ck check
    (warning_heading_all_caps in ('Y','N') or warning_heading_all_caps is null),
  constraint alv_verifications_bold_ck check
    (warning_heading_bold in ('Y','N') or warning_heading_bold is null)
);

create table alv_verification_fields (
  id                 number generated by default on null as identity,
  verification_id    number not null,
  display_sequence   number not null,
  field_code         varchar2(50) not null,
  field_label        varchar2(200) not null,
  expected_value     varchar2(4000),
  extracted_value    varchar2(4000),
  match_status       varchar2(30) not null,
  confidence         number(5,4),
  detail             varchar2(4000),
  constraint alv_verification_fields_pk primary key (id),
  constraint alv_verification_fields_ver_fk foreign key (verification_id)
    references alv_verifications (id) on delete cascade,
  constraint alv_verification_fields_status_ck check
    (match_status in ('MATCH','MISMATCH','MISSING','REVIEW','NOT_APPLICABLE'))
);

create index alv_verifications_batch_ix
  on alv_verifications (batch_id, created_at);

create index alv_verifications_created_ix
  on alv_verifications (created_at, overall_status);

create index alv_verification_fields_ver_ix
  on alv_verification_fields (verification_id, display_sequence);

create or replace view alv_batch_summary_v as
select b.id,
       b.public_token,
       b.manifest_file_name,
       b.zip_file_name,
       b.processing_mode,
       b.status,
       b.total_count,
       b.processed_count,
       b.pass_count,
       b.fail_count,
       b.review_count,
       b.processing_ms,
       b.notes,
       b.started_at,
       b.completed_at,
       b.created_by,
       case
         when b.total_count = 0 then 0
         else round(100 * b.processed_count / b.total_count, 1)
       end as percent_complete
  from alv_batches b;

insert into alv_config (config_key, config_value, description, updated_by)
values ('PROVIDER', 'DEMO',
        'DEMO works without external credentials. Set to OPENAI for live image extraction.',
        user);

insert into alv_config (config_key, config_value, description, updated_by)
values ('OPENAI_ENDPOINT', 'https://api.openai.com/v1/chat/completions',
        'Vision-capable Chat Completions endpoint.', user);

insert into alv_config (config_key, config_value, description, updated_by)
values ('OPENAI_CREDENTIAL_STATIC_ID', 'OPENAI_API_KEY',
        'APEX Web Credential static ID. The credential should send Authorization: Bearer <key>.',
        user);

insert into alv_config (config_key, config_value, description, updated_by)
values ('OPENAI_MODEL', 'gpt-5.6',
        'Vision-capable model available to the configured API account.', user);

insert into alv_config (config_key, config_value, description, updated_by)
values ('API_TIMEOUT_SECONDS', '12',
        'Outbound REST timeout for a single live verification.', user);

insert into alv_config (config_key, config_value, description, updated_by)
values ('MAX_FILE_BYTES', '10485760',
        'Maximum image size in bytes (default 10 MB).', user);

insert into alv_config (config_key, config_value, description, updated_by)
values ('MIN_CONFIDENCE', '0.75',
        'Below this extraction confidence, the result is routed to REVIEW.', user);

insert into alv_config (config_key, config_value, description, updated_by)
values ('ABV_TOLERANCE', '0.05',
        'Allowed absolute difference in ABV percentage points.', user);

insert into alv_config (config_key, config_value, description, updated_by)
values ('NET_TOLERANCE_ML', '2',
        'Allowed absolute difference after converting net contents to milliliters.', user);

insert into alv_config (config_key, config_value, description, updated_by)
values ('MAX_MANIFEST_BYTES', '2097152',
        'Maximum CSV manifest size in bytes (default 2 MB).', user);

insert into alv_config (config_key, config_value, description, updated_by)
values ('MAX_BATCH_ZIP_BYTES', '104857600',
        'Maximum compressed ZIP size in bytes (default 100 MB).', user);

insert into alv_config (config_key, config_value, description, updated_by)
values ('MAX_BATCH_UNCOMPRESSED_BYTES', '314572800',
        'Maximum total uncompressed ZIP size in bytes (default 300 MB).', user);

insert into alv_config (config_key, config_value, description, updated_by)
values ('MAX_BATCH_ITEMS', '300',
        'Maximum manifest rows accepted by the prototype batch upload.', user);

insert into alv_config (config_key, config_value, description, updated_by)
values ('MAX_SYNC_LIVE_BATCH_ITEMS', '25',
        'Safety cap for synchronous live API batch processing.', user);

insert into alv_config (config_key, config_value, description, updated_by)
values (
  'GOVERNMENT_WARNING',
  'GOVERNMENT WARNING: (1) According to the Surgeon General, women should not drink alcoholic beverages during pregnancy because of the risk of birth defects. (2) Consumption of alcoholic beverages impairs your ability to drive a car or operate machinery, and may cause health problems.',
  'Mandatory warning text from 27 CFR 16.21. Whitespace is normalized before exact comparison.',
  user
);

insert into alv_config (config_key, config_value, description, updated_by)
values ('TARGET_PROCESSING_MS', '5000',
        'Stakeholder target for a normal single-label live verification, in milliseconds.', user);

commit;
-- Alcohol Label Verification package hardening update
-- Non-destructive: replaces only ALV_VERIFICATION_PKG.
-- Fixes explicit provider selection, confidence precedence, and fatal batch messaging.
-- Run in APEX SQL Workshop -> SQL Scripts.

create or replace package alv_verification_pkg authid definer as
  function get_config(
    p_key      in varchar2,
    p_default  in varchar2 default null
  ) return varchar2;

  procedure set_config(
    p_key          in varchar2,
    p_value        in varchar2,
    p_description  in varchar2 default null
  );

  function government_warning return varchar2;

  procedure verify_label(
    p_file_name              in varchar2,
    p_mime_type              in varchar2,
    p_image_blob             in blob,
    p_application_ref        in varchar2,
    p_expected_brand_name    in varchar2,
    p_expected_class_type    in varchar2,
    p_expected_abv           in number,
    p_expected_net_contents  in varchar2,
    p_expected_producer      in varchar2,
    p_expected_country       in varchar2 default null,
    p_demo_profile           in varchar2 default null,
    p_batch_id               in number default null,
    p_verification_id        out number
  );

  procedure create_demo(
    p_profile          in varchar2,
    p_verification_id  out number
  );

  procedure process_batch(
    p_manifest_file_name  in varchar2,
    p_manifest_blob       in blob,
    p_zip_file_name       in varchar2,
    p_zip_blob            in blob,
    p_processing_mode     in varchar2,
    p_batch_id            out number
  );

end alv_verification_pkg;
/


create or replace package body alv_verification_pkg as
  c_warning constant varchar2(4000) :=
    'GOVERNMENT WARNING: (1) According to the Surgeon General, women should not drink alcoholic beverages during pregnancy because of the risk of birth defects. (2) Consumption of alcoholic beverages impairs your ability to drive a car or operate machinery, and may cause health problems.';

  function app_user return varchar2 is
  begin
    return substr(
      coalesce(
        sys_context('APEX$SESSION', 'APP_USER'),
        sys_context('USERENV', 'SESSION_USER')
      ),
      1,
      255
    );
  end app_user;

  function get_config(
    p_key      in varchar2,
    p_default  in varchar2 default null
  ) return varchar2 is
    l_value alv_config.config_value%type;
  begin
    select config_value
      into l_value
      from alv_config
     where config_key = upper(trim(p_key));

    return coalesce(l_value, p_default);
  exception
    when no_data_found then
      return p_default;
  end get_config;

  procedure set_config(
    p_key          in varchar2,
    p_value        in varchar2,
    p_description  in varchar2 default null
  ) is
    l_app_user varchar2(255) := app_user;
  begin
    merge into alv_config d
    using (
      select upper(trim(p_key)) as config_key,
             p_value as config_value,
             p_description as description
        from dual
    ) s
       on (d.config_key = s.config_key)
     when matched then update set
       d.config_value = s.config_value,
       d.description = coalesce(s.description, d.description),
       d.updated_at = systimestamp,
       d.updated_by = l_app_user
     when not matched then insert
       (config_key, config_value, description, updated_at, updated_by)
       values
       (s.config_key, s.config_value, s.description, systimestamp, l_app_user);
  end set_config;

  function government_warning return varchar2 is
  begin
    return c_warning;
  end government_warning;

  function normalize_whitespace(p_value in varchar2) return varchar2 is
  begin
    return trim(regexp_replace(p_value, '[[:space:]]+', ' '));
  end normalize_whitespace;

  function normalize_loose(p_value in varchar2) return varchar2 is
  begin
    return regexp_replace(lower(coalesce(p_value, '')), '[^[:alnum:]]', '');
  end normalize_loose;

  function safe_number(p_value in varchar2) return number is
    l_text varchar2(4000);
    l_num  varchar2(4000);
  begin
    l_text := trim(p_value);

    -- Treat a comma as a thousands separator only for forms such as 1,000.
    -- Otherwise, accept it as a decimal separator (for example 0,75).
    if instr(l_text, '.') = 0
       and regexp_like(l_text, '(^|[^0-9])[1-9][0-9]{0,2}(,[0-9]{3})+([^0-9]|$)') then
      l_text := replace(l_text, ',', '');
    else
      l_text := replace(l_text, ',', '.');
    end if;

    l_num := regexp_substr(l_text, '([0-9]+([.][0-9]+)?|[.][0-9]+)');

    if l_num is null then
      return null;
    elsif substr(l_num, 1, 1) = '.' then
      l_num := '0' || l_num;
    end if;

    if instr(l_num, '.') > 0 then
      return to_number(
        l_num,
        '99999999999999999999D99999999999999999999',
        'NLS_NUMERIC_CHARACTERS=''.,'''
      );
    else
      return to_number(
        l_num,
        '99999999999999999999',
        'NLS_NUMERIC_CHARACTERS=''.,'''
      );
    end if;
  exception
    when others then
      return null;
  end safe_number;

  function net_to_ml(p_value in varchar2) return number is
    l_text varchar2(4000) := lower(coalesce(p_value, ''));
    l_pair varchar2(4000);
    l_num  number;
  begin
    -- Use the first complete number/unit pair. This avoids treating the second
    -- unit in a dual declaration such as "1 L (33.8 fl oz)" as the primary one.
    l_pair := regexp_substr(
      l_text,
      '([0-9]+([.,][0-9]+)?|[.,][0-9]+)[[:space:]]*(fl[[:space:].]*oz|fluid[[:space:]]*ounces?|ml|milliliters?|millilitres?|cl|centiliters?|centilitres?|l|liters?|litres?)',
      1,
      1,
      'i'
    );
    l_num := safe_number(l_pair);

    if l_pair is null or l_num is null then
      return null;
    elsif regexp_like(l_pair, 'fl[[:space:].]*oz|fluid[[:space:]]*ounces?', 'i') then
      return l_num * 29.5735295625;
    elsif regexp_like(l_pair, '(^|[^a-z])(cl|centiliters?|centilitres?)', 'i') then
      return l_num * 10;
    elsif regexp_like(l_pair, '(^|[^a-z])(ml|milliliters?|millilitres?)', 'i') then
      return l_num;
    elsif regexp_like(l_pair, '(^|[^a-z])(l|liters?|litres?)', 'i') then
      return l_num * 1000;
    else
      return null;
    end if;
  end net_to_ml;

  function bool_to_yn(p_value in boolean) return char is
  begin
    if p_value is null then
      return null;
    elsif p_value then
      return 'Y';
    else
      return 'N';
    end if;
  end bool_to_yn;

  procedure add_result(
    p_verification_id  in number,
    p_sequence         in number,
    p_code             in varchar2,
    p_label            in varchar2,
    p_expected         in varchar2,
    p_extracted        in varchar2,
    p_status           in varchar2,
    p_confidence       in number,
    p_detail           in varchar2
  ) is
  begin
    insert into alv_verification_fields (
      verification_id,
      display_sequence,
      field_code,
      field_label,
      expected_value,
      extracted_value,
      match_status,
      confidence,
      detail
    ) values (
      p_verification_id,
      p_sequence,
      p_code,
      p_label,
      substr(p_expected, 1, 4000),
      substr(p_extracted, 1, 4000),
      p_status,
      p_confidence,
      substr(p_detail, 1, 4000)
    );
  end add_result;

  procedure build_results(
    p_verification_id            in number,
    p_expected_brand_name        in varchar2,
    p_expected_class_type        in varchar2,
    p_expected_abv               in number,
    p_expected_net_contents      in varchar2,
    p_expected_producer          in varchar2,
    p_expected_country           in varchar2,
    p_extracted_brand_name       in varchar2,
    p_extracted_class_type       in varchar2,
    p_extracted_abv              in number,
    p_extracted_net_contents     in varchar2,
    p_extracted_producer         in varchar2,
    p_extracted_country          in varchar2,
    p_extracted_warning          in varchar2,
    p_warning_heading_all_caps   in char,
    p_warning_heading_bold       in char,
    p_confidence                 in number,
    p_overall_status             out varchar2
  ) is
    l_status             varchar2(30);
    l_detail             varchar2(4000);
    l_expected_ml        number;
    l_extracted_ml       number;
    l_min_confidence     number := safe_number(get_config('MIN_CONFIDENCE', '0.75'));
    l_abv_tolerance      number := safe_number(get_config('ABV_TOLERANCE', '0.05'));
    l_net_tolerance      number := safe_number(get_config('NET_TOLERANCE_ML', '2'));
    l_fail_count         number;
    l_review_count       number;
    l_expected_loose     varchar2(4000);
    l_extracted_loose    varchar2(4000);
    l_length_ratio       number;
  begin
    delete from alv_verification_fields
     where verification_id = p_verification_id;

    if p_extracted_brand_name is null then
      l_status := 'MISSING';
      l_detail := 'No brand name could be read from the label.';
    elsif normalize_loose(p_expected_brand_name) = normalize_loose(p_extracted_brand_name) then
      l_status := 'MATCH';
      l_detail := 'Case, spacing, and punctuation differences are intentionally ignored.';
    else
      l_status := 'MISMATCH';
      l_detail := 'The normalized brand names differ.';
    end if;
    add_result(p_verification_id, 10, 'BRAND_NAME', 'Brand name',
               p_expected_brand_name, p_extracted_brand_name,
               l_status, p_confidence, l_detail);

    if p_extracted_class_type is null then
      l_status := 'MISSING';
      l_detail := 'No class/type designation could be read from the label.';
    elsif normalize_loose(p_expected_class_type) = normalize_loose(p_extracted_class_type) then
      l_status := 'MATCH';
      l_detail := 'Case, spacing, and punctuation differences are ignored.';
    else
      l_status := 'MISMATCH';
      l_detail := 'The normalized class/type designations differ.';
    end if;
    add_result(p_verification_id, 20, 'CLASS_TYPE', 'Class / type',
               p_expected_class_type, p_extracted_class_type,
               l_status, p_confidence, l_detail);

    if p_extracted_abv is null then
      l_status := 'MISSING';
      l_detail := 'No ABV percentage could be read from the label.';
    elsif abs(p_expected_abv - p_extracted_abv) <= coalesce(l_abv_tolerance, 0.05) then
      l_status := 'MATCH';
      l_detail := 'Compared numerically using the configured ABV tolerance.';
    else
      l_status := 'MISMATCH';
      l_detail := 'The extracted ABV differs from the application value.';
    end if;
    add_result(p_verification_id, 30, 'ABV', 'Alcohol by volume',
               to_char(p_expected_abv, 'FM990D999', 'NLS_NUMERIC_CHARACTERS=''.,''') || '%',
               case when p_extracted_abv is not null
                    then to_char(p_extracted_abv, 'FM990D999', 'NLS_NUMERIC_CHARACTERS=''.,''') || '%'
               end,
               l_status, p_confidence, l_detail);

    l_expected_ml := net_to_ml(p_expected_net_contents);
    l_extracted_ml := net_to_ml(p_extracted_net_contents);
    if p_extracted_net_contents is null then
      l_status := 'MISSING';
      l_detail := 'No net contents could be read from the label.';
    elsif l_expected_ml is null or l_extracted_ml is null then
      l_status := 'REVIEW';
      l_detail := 'The value was present, but its number or unit could not be normalized.';
    elsif abs(l_expected_ml - l_extracted_ml) <= coalesce(l_net_tolerance, 2) then
      l_status := 'MATCH';
      l_detail := 'Values were converted to milliliters before comparison.';
    else
      l_status := 'MISMATCH';
      l_detail := 'The normalized net contents differ.';
    end if;
    add_result(p_verification_id, 40, 'NET_CONTENTS', 'Net contents',
               p_expected_net_contents, p_extracted_net_contents,
               l_status, p_confidence, l_detail);

    if p_expected_producer is null then
      l_status := 'NOT_APPLICABLE';
      l_detail := 'No producer value was supplied in the application data.';
    elsif p_extracted_producer is null then
      l_status := 'MISSING';
      l_detail := 'No bottler/producer name and address could be read.';
    else
      l_expected_loose := normalize_loose(p_expected_producer);
      l_extracted_loose := normalize_loose(p_extracted_producer);
      if l_extracted_loose is null then
        l_status := 'MISSING';
        l_detail := 'The extracted producer/address contains no usable text.';
      else
        l_length_ratio := least(length(l_expected_loose), length(l_extracted_loose)) /
                          greatest(length(l_expected_loose), length(l_extracted_loose));
        if l_expected_loose = l_extracted_loose
           or ((instr(l_expected_loose, l_extracted_loose) > 0
                or instr(l_extracted_loose, l_expected_loose) > 0)
               and l_length_ratio >= 0.70) then
          l_status := 'MATCH';
          l_detail := 'Case, spacing, punctuation, and short regulatory prefixes are ignored.';
        else
          l_status := 'MISMATCH';
          l_detail := 'The producer/address text differs materially or is incomplete.';
        end if;
      end if;
    end if;
    add_result(p_verification_id, 50, 'PRODUCER', 'Bottler / producer',
               p_expected_producer, p_extracted_producer,
               l_status, p_confidence, l_detail);

    if p_expected_country is null then
      l_status := 'NOT_APPLICABLE';
      l_detail := 'Country of origin was not supplied; this may be a domestic product.';
    elsif p_extracted_country is null then
      l_status := 'MISSING';
      l_detail := 'No country of origin could be read from the label.';
    elsif normalize_loose(p_expected_country) = normalize_loose(p_extracted_country) then
      l_status := 'MATCH';
      l_detail := 'Case, spacing, and punctuation differences are ignored.';
    else
      l_status := 'MISMATCH';
      l_detail := 'The country of origin differs from the application.';
    end if;
    add_result(p_verification_id, 60, 'COUNTRY', 'Country of origin',
               p_expected_country, p_extracted_country,
               l_status, p_confidence, l_detail);

    if p_extracted_warning is null then
      l_status := 'MISSING';
      l_detail := 'The mandatory government warning was not detected.';
    elsif normalize_whitespace(p_extracted_warning) = normalize_whitespace(c_warning) then
      l_status := 'MATCH';
      l_detail := 'The wording and punctuation match after normalizing line breaks and repeated spaces.';
    else
      l_status := 'MISMATCH';
      l_detail := 'The warning must match the mandatory wording exactly; only whitespace is normalized.';
    end if;
    add_result(p_verification_id, 70, 'WARNING_TEXT', 'Government warning text',
               c_warning, p_extracted_warning,
               l_status, p_confidence, l_detail);

    if p_extracted_warning is null then
      l_status := 'MISSING';
      l_detail := 'The warning heading was not detected.';
    elsif p_warning_heading_all_caps = 'Y'
          and regexp_like(ltrim(p_extracted_warning), '^GOVERNMENT WARNING:') then
      l_status := 'MATCH';
      l_detail := 'The heading is presented in capital letters.';
    elsif p_warning_heading_all_caps is null then
      l_status := 'REVIEW';
      l_detail := 'The extraction service could not determine heading capitalization reliably.';
    else
      l_status := 'MISMATCH';
      l_detail := 'The heading must begin with GOVERNMENT WARNING: in capital letters.';
    end if;
    add_result(p_verification_id, 80, 'WARNING_CAPS', 'Warning heading capitalization',
               'GOVERNMENT WARNING: (all caps)',
               case p_warning_heading_all_caps when 'Y' then 'All caps' when 'N' then 'Not all caps' end,
               l_status, p_confidence, l_detail);

    if p_extracted_warning is null then
      l_status := 'MISSING';
      l_detail := 'The warning heading was not detected.';
    elsif p_warning_heading_bold = 'Y' then
      l_status := 'MATCH';
      l_detail := 'The first two words are visually bold.';
    elsif p_warning_heading_bold is null then
      l_status := 'REVIEW';
      l_detail := 'The extraction service could not determine bold styling reliably.';
    else
      l_status := 'MISMATCH';
      l_detail := 'GOVERNMENT WARNING must be in bold type.';
    end if;
    add_result(p_verification_id, 90, 'WARNING_BOLD', 'Warning heading bold',
               'Bold',
               case p_warning_heading_bold when 'Y' then 'Bold' when 'N' then 'Not bold' end,
               l_status, p_confidence, l_detail);

    if p_confidence is null then
      l_status := 'REVIEW';
      l_detail := 'The extraction provider did not return a confidence score.';
    elsif p_confidence < coalesce(l_min_confidence, 0.75) then
      l_status := 'REVIEW';
      l_detail := 'Low-confidence results require human review even when field values appear to match.';
    else
      l_status := 'MATCH';
      l_detail := 'The extraction confidence meets the configured threshold.';
    end if;
    add_result(p_verification_id, 100, 'CONFIDENCE', 'Extraction confidence',
               '>=' || to_char(coalesce(l_min_confidence, 0.75) * 100, 'FM990D0') || '%',
               case when p_confidence is not null
                    then to_char(p_confidence * 100, 'FM990D0') || '%'
               end,
               l_status, p_confidence, l_detail);

    select sum(case when match_status in ('MISMATCH', 'MISSING') then 1 else 0 end),
           sum(case when match_status = 'REVIEW' then 1 else 0 end)
      into l_fail_count, l_review_count
      from alv_verification_fields
     where verification_id = p_verification_id;

    -- Extraction reliability takes precedence over apparent mismatches. A low-
    -- confidence or missing-confidence extraction must be reviewed by a person;
    -- it must not automatically reject a label based on uncertain evidence.
    if p_confidence is null
       or p_confidence < coalesce(l_min_confidence, 0.75) then
      p_overall_status := 'REVIEW';
    elsif coalesce(l_fail_count, 0) > 0 then
      p_overall_status := 'FAIL';
    elsif coalesce(l_review_count, 0) > 0 then
      p_overall_status := 'REVIEW';
    else
      p_overall_status := 'PASS';
    end if;
  end build_results;

  procedure demo_extract(
    p_profile                    in varchar2,
    p_expected_brand_name        in varchar2,
    p_expected_class_type        in varchar2,
    p_expected_abv               in number,
    p_expected_net_contents      in varchar2,
    p_expected_producer          in varchar2,
    p_expected_country           in varchar2,
    p_brand_name                 out varchar2,
    p_class_type                 out varchar2,
    p_abv                        out number,
    p_net_contents               out varchar2,
    p_producer                   out varchar2,
    p_country                    out varchar2,
    p_warning                    out varchar2,
    p_warning_all_caps           out char,
    p_warning_bold               out char,
    p_raw_text                   out clob,
    p_confidence                 out number
  ) is
    l_profile varchar2(30) := upper(coalesce(trim(p_profile), 'PASS'));
  begin
    p_brand_name := p_expected_brand_name;
    if normalize_loose(p_expected_brand_name) = normalize_loose('STONE''S THROW') then
      p_brand_name := 'Stone''s Throw';
    end if;
    p_class_type := p_expected_class_type;
    p_abv := p_expected_abv;
    p_net_contents := p_expected_net_contents;
    if abs(coalesce(net_to_ml(p_expected_net_contents), -1) - 750) < 0.01 then
      p_net_contents := '0.75 L';
    end if;
    p_producer := p_expected_producer;
    if normalize_loose(p_expected_producer) =
       normalize_loose('Bottled by Stone''s Throw Distilling Co., Louisville, KY') then
      p_producer := 'Stone''s Throw Distilling Co., Louisville, KY';
    end if;
    p_country := p_expected_country;
    p_warning := c_warning;
    p_warning_all_caps := 'Y';
    p_warning_bold := 'Y';
    p_confidence := 0.97;

    if l_profile = 'BRAND_MISMATCH' then
      p_brand_name := 'NORTH STAR RESERVE';
      p_confidence := 0.96;
    elsif l_profile = 'WARNING_ERROR' then
      p_warning := replace(c_warning, 'GOVERNMENT WARNING:', 'Government Warning:');
      p_warning_all_caps := 'N';
      p_warning_bold := 'N';
      p_confidence := 0.94;
    elsif l_profile = 'LOW_CONFIDENCE' then
      p_confidence := 0.52;
    elsif l_profile = 'MISSING_ABV' then
      p_abv := null;
      p_confidence := 0.91;
    elsif l_profile != 'PASS' then
      raise_application_error(-20020, 'Unknown demo profile: ' || l_profile);
    end if;

    p_raw_text :=
      coalesce(p_brand_name, '') || chr(10) ||
      coalesce(p_class_type, '') || chr(10) ||
      case when p_abv is not null then to_char(p_abv, 'FM990D999') || '% Alc./Vol.' end || chr(10) ||
      coalesce(p_net_contents, '') || chr(10) ||
      coalesce(p_producer, '') || chr(10) ||
      coalesce(p_country, '') || chr(10) ||
      coalesce(p_warning, '');
  end demo_extract;

  procedure append_text(
    p_target in out nocopy clob,
    p_text   in varchar2
  ) is
  begin
    if p_text is not null then
      dbms_lob.writeappend(p_target, length(p_text), p_text);
    end if;
  end append_text;

  function strip_code_fence(p_text in varchar2) return varchar2 is
    l_text varchar2(32767) := trim(p_text);
  begin
    if substr(l_text, 1, 3) = '```' then
      l_text := regexp_replace(l_text, '^```[[:alpha:]]*[[:space:]]*', '');
      l_text := regexp_replace(l_text, '[[:space:]]*```$', '');
    end if;
    return trim(l_text);
  end strip_code_fence;

  procedure openai_extract(
    p_mime_type                  in varchar2,
    p_image_blob                 in blob,
    p_brand_name                 out varchar2,
    p_class_type                 out varchar2,
    p_abv                        out number,
    p_net_contents               out varchar2,
    p_producer                   out varchar2,
    p_country                    out varchar2,
    p_warning                    out varchar2,
    p_warning_all_caps           out char,
    p_warning_bold               out char,
    p_raw_text                   out clob,
    p_confidence                 out number,
    p_http_status                out number,
    p_provider_response          out clob
  ) is
    l_endpoint       varchar2(4000) := get_config('OPENAI_ENDPOINT');
    l_credential     varchar2(255)  := get_config('OPENAI_CREDENTIAL_STATIC_ID');
    l_model          varchar2(255)  := get_config('OPENAI_MODEL', 'gpt-5.6');
    l_timeout        number         := safe_number(get_config('API_TIMEOUT_SECONDS', '12'));
    l_prompt         varchar2(32767);
    l_base64         clob;
    l_request        clob;
    l_response       clob;
    l_root           json_object_t;
    l_choices        json_array_t;
    l_choice         json_object_t;
    l_message        json_object_t;
    l_content        varchar2(32767);
    l_result         json_object_t;
    l_bool           boolean;
  begin
    if l_endpoint is null or l_credential is null or l_model is null then
      raise_application_error(-20030, 'Live provider configuration is incomplete.');
    end if;

    l_prompt :=
      'Read this alcohol beverage label. Return ONLY one valid JSON object with exactly these keys: ' ||
      'brand_name, class_type, abv_percent, net_contents, producer_name_address, country_of_origin, ' ||
      'government_warning_text, government_warning_heading_all_caps, government_warning_heading_bold, ' ||
      'raw_text, confidence. Use JSON null for unreadable values. abv_percent must be a number, and ' ||
      'confidence must be from 0 to 1. Preserve the government warning wording, capitalization, and ' ||
      'punctuation exactly as seen; do not correct or normalize it. Inspect the image itself to decide ' ||
      'whether the words GOVERNMENT WARNING are all capitals and visually bold. Do not infer missing text.';

    l_base64 := apex_web_service.blob2clobbase64(
      p_blob     => p_image_blob,
      p_newlines => 'N',
      p_padding  => 'Y'
    );

    dbms_lob.createtemporary(l_request, true, dbms_lob.call);
    append_text(
      l_request,
      '{"model":' || apex_json.stringify(l_model) ||
      ',"messages":[{"role":"user","content":[' ||
      '{"type":"text","text":' || apex_json.stringify(l_prompt) || '},' ||
      '{"type":"image_url","image_url":{"url":"data:' || lower(p_mime_type) || ';base64,'
    );
    dbms_lob.append(l_request, l_base64);
    append_text(
      l_request,
      '"}}]}],"max_completion_tokens":1500,"response_format":{"type":"json_object"}}'
    );

    apex_web_service.g_request_headers.delete;
    apex_web_service.g_request_headers(1).name := 'Content-Type';
    apex_web_service.g_request_headers(1).value := 'application/json';
    apex_web_service.g_request_headers(2).name := 'Accept';
    apex_web_service.g_request_headers(2).value := 'application/json';

    l_response := apex_web_service.make_rest_request(
      p_url                  => l_endpoint,
      p_http_method          => 'POST',
      p_body                 => l_request,
      p_credential_static_id => l_credential,
      p_transfer_timeout     => coalesce(l_timeout, 12)
    );

    p_http_status := apex_web_service.g_status_code;
    p_provider_response := l_response;

    if p_http_status < 200 or p_http_status >= 300 then
      raise_application_error(
        -20031,
        'Vision service returned HTTP ' || p_http_status || ': ' ||
        substr(dbms_lob.substr(l_response, 1000, 1), 1, 1000)
      );
    end if;

    l_root := json_object_t.parse(l_response);
    l_choices := l_root.get_array('choices');
    if l_choices is null or l_choices.get_size = 0 then
      raise_application_error(-20032, 'Vision service response did not contain a choice.');
    end if;

    l_choice := treat(l_choices.get(0) as json_object_t);
    l_message := l_choice.get_object('message');
    l_content := strip_code_fence(l_message.get_string('content'));
    l_result := json_object_t.parse(l_content);

    p_brand_name := l_result.get_string('brand_name');
    p_class_type := l_result.get_string('class_type');
    p_abv := l_result.get_number('abv_percent');
    p_net_contents := l_result.get_string('net_contents');
    p_producer := l_result.get_string('producer_name_address');
    p_country := l_result.get_string('country_of_origin');
    p_warning := l_result.get_string('government_warning_text');

    l_bool := l_result.get_boolean('government_warning_heading_all_caps');
    p_warning_all_caps := bool_to_yn(l_bool);
    l_bool := l_result.get_boolean('government_warning_heading_bold');
    p_warning_bold := bool_to_yn(l_bool);

    p_raw_text := l_result.get_clob('raw_text');
    p_confidence := l_result.get_number('confidence');

    if p_confidence is not null then
      p_confidence := greatest(0, least(1, p_confidence));
    end if;

    if dbms_lob.istemporary(l_base64) = 1 then
      dbms_lob.freetemporary(l_base64);
    end if;
    if dbms_lob.istemporary(l_request) = 1 then
      dbms_lob.freetemporary(l_request);
    end if;
  exception
    when others then
      if l_base64 is not null and dbms_lob.istemporary(l_base64) = 1 then
        dbms_lob.freetemporary(l_base64);
      end if;
      if l_request is not null and dbms_lob.istemporary(l_request) = 1 then
        dbms_lob.freetemporary(l_request);
      end if;
      raise;
  end openai_extract;

  function file_basename(p_path in varchar2) return varchar2 is
    l_path varchar2(4000) := replace(p_path, chr(92), '/');
  begin
    return regexp_substr(l_path, '[^/]+$');
  end file_basename;

  function mime_from_name(p_file_name in varchar2) return varchar2 is
    l_ext varchar2(50) := lower(substr(p_file_name, instr(p_file_name, '.', -1) + 1));
  begin
    return case l_ext
      when 'jpg' then 'image/jpeg'
      when 'jpeg' then 'image/jpeg'
      when 'png' then 'image/png'
      when 'webp' then 'image/webp'
      when 'gif' then 'image/gif'
      else 'application/octet-stream'
    end;
  end mime_from_name;

  function effective_mime(
    p_file_name in varchar2,
    p_mime_type in varchar2
  ) return varchar2 is
    l_mime varchar2(255) := lower(regexp_substr(trim(p_mime_type), '^[^;]+'));
  begin
    if l_mime = 'image/jpg' then
      return 'image/jpeg';
    elsif l_mime in ('image/jpeg', 'image/png', 'image/webp', 'image/gif') then
      return l_mime;
    else
      return mime_from_name(p_file_name);
    end if;
  end effective_mime;

  function normalize_header(p_value in varchar2) return varchar2 is
    l_value varchar2(4000);
  begin
    l_value := lower(trim(replace(p_value, unistr('\FEFF'), '')));
    l_value := regexp_replace(l_value, '[^a-z0-9]+', '_');
    return regexp_replace(l_value, '^_+|_+$', '');
  end normalize_header;

  procedure validate_input(
    p_file_name              in varchar2,
    p_mime_type              in varchar2,
    p_image_blob             in blob,
    p_application_ref        in varchar2,
    p_expected_brand_name    in varchar2,
    p_expected_class_type    in varchar2,
    p_expected_abv           in number,
    p_expected_net_contents  in varchar2,
    p_expected_producer      in varchar2,
    p_is_demo                in boolean
  ) is
    l_max_bytes number := safe_number(get_config('MAX_FILE_BYTES', '10485760'));
    l_mime      varchar2(255) := lower(trim(p_mime_type));
  begin
    if trim(p_application_ref) is null then
      raise_application_error(-20001, 'Application reference is required.');
    elsif trim(p_expected_brand_name) is null or normalize_loose(p_expected_brand_name) is null then
      raise_application_error(-20002, 'Expected brand name is required and must contain letters or numbers.');
    elsif trim(p_expected_class_type) is null or normalize_loose(p_expected_class_type) is null then
      raise_application_error(-20003, 'Expected class/type is required and must contain letters or numbers.');
    elsif p_expected_abv is null or p_expected_abv < 0 or p_expected_abv > 100 then
      raise_application_error(-20004, 'Expected ABV must be between 0 and 100.');
    elsif trim(p_expected_net_contents) is null or net_to_ml(p_expected_net_contents) is null then
      raise_application_error(-20005, 'Expected net contents must include a supported number and unit.');
    elsif trim(p_expected_producer) is null or normalize_loose(p_expected_producer) is null then
      raise_application_error(-20006, 'Expected bottler/producer is required and must contain letters or numbers.');
    end if;

    if p_image_blob is null then
      if not p_is_demo then
        raise_application_error(-20007, 'A label image is required for live verification.');
      end if;
    else
      if trim(p_file_name) is null then
        raise_application_error(-20007, 'The uploaded image file name is missing.');
      elsif dbms_lob.getlength(p_image_blob) > coalesce(l_max_bytes, 10485760) then
        raise_application_error(-20008, 'The image exceeds the configured size limit.');
      elsif l_mime not in ('image/jpeg', 'image/png', 'image/webp', 'image/gif') then
        raise_application_error(-20009, 'Upload a JPEG, PNG, WEBP, or GIF image.');
      end if;
    end if;
  end validate_input;

  procedure verify_label(
    p_file_name              in varchar2,
    p_mime_type              in varchar2,
    p_image_blob             in blob,
    p_application_ref        in varchar2,
    p_expected_brand_name    in varchar2,
    p_expected_class_type    in varchar2,
    p_expected_abv           in number,
    p_expected_net_contents  in varchar2,
    p_expected_producer      in varchar2,
    p_expected_country       in varchar2 default null,
    p_demo_profile           in varchar2 default null,
    p_batch_id               in number default null,
    p_verification_id        out number
  ) is
    l_start                      number := dbms_utility.get_time;
    l_provider                   varchar2(30) := upper(get_config('PROVIDER', 'DEMO'));
    l_profile                    varchar2(30) := upper(trim(p_demo_profile));
    l_is_demo                    boolean;
    l_brand_name                 varchar2(500);
    l_class_type                 varchar2(1000);
    l_abv                        number;
    l_net_contents               varchar2(200);
    l_producer                   varchar2(1000);
    l_country                    varchar2(500);
    l_warning                    varchar2(4000);
    l_warning_all_caps           char(1);
    l_warning_bold               char(1);
    l_raw_text                   clob;
    l_confidence                 number;
    l_http_status                number;
    l_provider_response          clob;
    l_overall_status             varchar2(20);
    l_elapsed_ms                 number;
    l_error_message              varchar2(4000);
    l_app_user                   varchar2(255) := app_user;
    l_effective_mime             varchar2(255) := effective_mime(p_file_name, p_mime_type);
  begin
    if l_profile is not null then
      l_provider := 'DEMO';
    end if;

    -- Never disguise an unconfigured live-provider request as a passing demo.
    -- Demo behavior must always be explicitly selected by the caller.
    if l_provider = 'DEMO' and l_profile is null then
      raise_application_error(
        -20011,
        'Live image analysis is not configured. Select a Demo mode or set ALV_CONFIG.PROVIDER to OPENAI and configure the APEX Web Credential.'
      );
    end if;

    l_is_demo := (l_provider = 'DEMO');

    validate_input(
      p_file_name,
      l_effective_mime,
      p_image_blob,
      p_application_ref,
      p_expected_brand_name,
      p_expected_class_type,
      p_expected_abv,
      p_expected_net_contents,
      p_expected_producer,
      l_is_demo
    );

    insert into alv_verifications (
      public_token,
      batch_id,
      application_ref,
      file_name,
      mime_type,
      image_blob,
      expected_brand_name,
      expected_class_type,
      expected_abv,
      expected_net_contents,
      expected_producer,
      expected_country,
      provider,
      demo_profile,
      overall_status,
      created_by
    ) values (
      lower(rawtohex(sys_guid())),
      p_batch_id,
      trim(p_application_ref),
      p_file_name,
      l_effective_mime,
      p_image_blob,
      trim(p_expected_brand_name),
      trim(p_expected_class_type),
      p_expected_abv,
      trim(p_expected_net_contents),
      trim(p_expected_producer),
      trim(p_expected_country),
      l_provider,
      l_profile,
      'PROCESSING',
      l_app_user
    ) returning id into p_verification_id;

    begin
      if l_provider = 'DEMO' then
        demo_extract(
          l_profile,
          p_expected_brand_name,
          p_expected_class_type,
          p_expected_abv,
          p_expected_net_contents,
          p_expected_producer,
          p_expected_country,
          l_brand_name,
          l_class_type,
          l_abv,
          l_net_contents,
          l_producer,
          l_country,
          l_warning,
          l_warning_all_caps,
          l_warning_bold,
          l_raw_text,
          l_confidence
        );
      elsif l_provider = 'OPENAI' then
        openai_extract(
          l_effective_mime,
          p_image_blob,
          l_brand_name,
          l_class_type,
          l_abv,
          l_net_contents,
          l_producer,
          l_country,
          l_warning,
          l_warning_all_caps,
          l_warning_bold,
          l_raw_text,
          l_confidence,
          l_http_status,
          l_provider_response
        );
      else
        raise_application_error(-20010, 'Unsupported provider: ' || l_provider);
      end if;

      build_results(
        p_verification_id,
        p_expected_brand_name,
        p_expected_class_type,
        p_expected_abv,
        p_expected_net_contents,
        p_expected_producer,
        p_expected_country,
        l_brand_name,
        l_class_type,
        l_abv,
        l_net_contents,
        l_producer,
        l_country,
        l_warning,
        l_warning_all_caps,
        l_warning_bold,
        l_confidence,
        l_overall_status
      );

      l_elapsed_ms := round((dbms_utility.get_time - l_start) * 10);

      update alv_verifications
         set extracted_brand_name = l_brand_name,
             extracted_class_type = l_class_type,
             extracted_abv = l_abv,
             extracted_net_contents = l_net_contents,
             extracted_producer = l_producer,
             extracted_country = l_country,
             extracted_warning = l_warning,
             warning_heading_all_caps = l_warning_all_caps,
             warning_heading_bold = l_warning_bold,
             extracted_text = l_raw_text,
             provider_response = l_provider_response,
             overall_status = l_overall_status,
             confidence = l_confidence,
             processing_ms = l_elapsed_ms,
             http_status = l_http_status,
             error_message = null
       where id = p_verification_id;
    exception
      when others then
        l_error_message := substr(sqlerrm, 1, 4000);
        l_elapsed_ms := round((dbms_utility.get_time - l_start) * 10);

        delete from alv_verification_fields
         where verification_id = p_verification_id;

        add_result(
          p_verification_id,
          10,
          'PROVIDER_ERROR',
          'Extraction service',
          'Successful extraction',
          'Error',
          'REVIEW',
          null,
          l_error_message
        );

        update alv_verifications
           set provider_response = l_provider_response,
               overall_status = 'REVIEW',
               processing_ms = l_elapsed_ms,
               http_status = l_http_status,
               error_message = l_error_message
         where id = p_verification_id;
    end;
  end verify_label;

  procedure create_demo(
    p_profile          in varchar2,
    p_verification_id  out number
  ) is
  begin
    verify_label(
      p_file_name              => 'demo-' || lower(trim(p_profile)) || '.png',
      p_mime_type              => 'image/png',
      p_image_blob             => null,
      p_application_ref        => 'DEMO-' || to_char(systimestamp, 'YYYYMMDDHH24MISSFF3'),
      p_expected_brand_name    => 'STONE''S THROW',
      p_expected_class_type    => 'Kentucky Straight Bourbon Whiskey',
      p_expected_abv           => 45,
      p_expected_net_contents  => '750 mL',
      p_expected_producer      => 'Bottled by Stone''s Throw Distilling Co., Louisville, KY',
      p_expected_country       => null,
      p_demo_profile           => upper(trim(p_profile)),
      p_batch_id               => null,
      p_verification_id        => p_verification_id
    );
  end create_demo;

  procedure insert_batch_error(
    p_batch_id           in number,
    p_application_ref    in varchar2,
    p_file_name          in varchar2,
    p_brand_name         in varchar2,
    p_class_type         in varchar2,
    p_abv                in number,
    p_net_contents       in varchar2,
    p_producer           in varchar2,
    p_country            in varchar2,
    p_message            in varchar2
  ) is
    l_id       number;
    l_app_user varchar2(255) := app_user;
  begin
    insert into alv_verifications (
      public_token,
      batch_id,
      application_ref,
      file_name,
      expected_brand_name,
      expected_class_type,
      expected_abv,
      expected_net_contents,
      expected_producer,
      expected_country,
      provider,
      overall_status,
      error_message,
      created_by
    ) values (
      lower(rawtohex(sys_guid())),
      p_batch_id,
      coalesce(trim(p_application_ref), 'UNIDENTIFIED'),
      p_file_name,
      p_brand_name,
      p_class_type,
      p_abv,
      p_net_contents,
      p_producer,
      p_country,
      'BATCH',
      'REVIEW',
      substr(p_message, 1, 4000),
      l_app_user
    ) returning id into l_id;

    add_result(
      l_id,
      10,
      'BATCH_INPUT',
      'Batch input',
      'Valid manifest row and matching image',
      'Input error',
      'REVIEW',
      null,
      p_message
    );
  end insert_batch_error;

  procedure process_batch(
    p_manifest_file_name  in varchar2,
    p_manifest_blob       in blob,
    p_zip_file_name       in varchar2,
    p_zip_blob            in blob,
    p_processing_mode     in varchar2,
    p_batch_id            out number
  ) is
    l_start             number := dbms_utility.get_time;
    l_mode              varchar2(30) := upper(coalesce(trim(p_processing_mode), 'CONFIGURED'));
    l_provider          varchar2(30) := upper(get_config('PROVIDER', 'DEMO'));
    l_max_items         number := safe_number(get_config('MAX_BATCH_ITEMS', '300'));
    l_live_limit        number := safe_number(get_config('MAX_SYNC_LIVE_BATCH_ITEMS', '25'));
    l_max_manifest      number := safe_number(get_config('MAX_MANIFEST_BYTES', '2097152'));
    l_max_zip           number := safe_number(get_config('MAX_BATCH_ZIP_BYTES', '104857600'));
    l_max_uncompressed  number := safe_number(get_config('MAX_BATCH_UNCOMPRESSED_BYTES', '314572800'));
    l_max_file          number := safe_number(get_config('MAX_FILE_BYTES', '10485760'));
    l_manifest_count    number;
    l_zip_entries       apex_zip.t_dir_entries;
    l_zip_key           varchar2(32767);
    l_zip_entry         varchar2(32767);
    l_image_blob        blob;
    l_mime_type         varchar2(255);
    l_demo_profile      varchar2(30);
    l_verification_id   number;
    l_row_number        number := 0;
    l_abv               number;
    l_processed         number;
    l_pass              number;
    l_fail              number;
    l_review            number;
    l_elapsed_ms        number;
    l_uncompressed_total number := 0;
    l_match_count       number;
    l_lookup_error      varchar2(4000);
    l_h1                varchar2(100);
    l_h2                varchar2(100);
    l_h3                varchar2(100);
    l_h4                varchar2(100);
    l_h5                varchar2(100);
    l_h6                varchar2(100);
    l_h7                varchar2(100);
    l_h8                varchar2(100);
    l_h9                varchar2(100);
    l_error_message      varchar2(4000);
    l_app_user           varchar2(255) := app_user;
  begin
    if p_manifest_blob is null then
      raise_application_error(-20040, 'A CSV manifest is required.');
    elsif p_zip_blob is null then
      raise_application_error(-20041, 'A ZIP archive containing label images is required.');
    elsif trim(p_manifest_file_name) is null or lower(p_manifest_file_name) not like '%.csv' then
      raise_application_error(-20047, 'The manifest must be a CSV file.');
    elsif trim(p_zip_file_name) is null or lower(p_zip_file_name) not like '%.zip' then
      raise_application_error(-20048, 'The image archive must be a ZIP file.');
    elsif dbms_lob.getlength(p_manifest_blob) > coalesce(l_max_manifest, 2097152) then
      raise_application_error(-20049, 'The CSV manifest exceeds the configured size limit.');
    elsif dbms_lob.getlength(p_zip_blob) > coalesce(l_max_zip, 104857600) then
      raise_application_error(-20051, 'The ZIP archive exceeds the configured compressed size limit.');
    elsif l_mode not in ('CONFIGURED', 'DEMO_MIXED', 'PASS', 'BRAND_MISMATCH', 'WARNING_ERROR', 'LOW_CONFIDENCE', 'MISSING_ABV') then
      raise_application_error(-20042, 'Unsupported batch processing mode: ' || l_mode);
    elsif l_mode = 'CONFIGURED' and l_provider = 'DEMO' then
      raise_application_error(
        -20058,
        'Live batch analysis is not configured. Select a Demo mode or set ALV_CONFIG.PROVIDER to OPENAI and configure the APEX Web Credential.'
      );
    end if;

    insert into alv_batches (
      public_token,
      manifest_file_name,
      zip_file_name,
      processing_mode,
      status,
      started_at,
      created_by
    ) values (
      lower(rawtohex(sys_guid())),
      p_manifest_file_name,
      p_zip_file_name,
      l_mode,
      'PROCESSING',
      systimestamp,
      l_app_user
    ) returning id into p_batch_id;

    begin
      begin
        select col001,
               col002,
               col003,
               col004,
               col005,
               col006,
               col007,
               col008,
               col009
          into l_h1, l_h2, l_h3, l_h4, l_h5, l_h6, l_h7, l_h8, l_h9
          from table(
            apex_data_parser.parse(
              p_content                => p_manifest_blob,
              p_file_name              => p_manifest_file_name,
              p_detect_data_types      => 'N',
              p_force_trim_whitespace  => 'Y',
              p_max_rows               => 1
            )
          )
         where line_number = 1;
      exception
        when no_data_found then
          raise_application_error(-20052, 'The manifest is empty or cannot be parsed.');
      end;

      l_h1 := normalize_header(l_h1);
      l_h2 := normalize_header(l_h2);
      l_h3 := normalize_header(l_h3);
      l_h4 := normalize_header(l_h4);
      l_h5 := normalize_header(l_h5);
      l_h6 := normalize_header(l_h6);
      l_h7 := normalize_header(l_h7);
      l_h8 := normalize_header(l_h8);
      l_h9 := normalize_header(l_h9);

      if coalesce(l_h1, '~') != 'file_name'
         or coalesce(l_h2, '~') != 'application_ref'
         or coalesce(l_h3, '~') != 'brand_name'
         or coalesce(l_h4, '~') not in ('class_type', 'class_or_type')
         or coalesce(l_h5, '~') not in ('abv', 'abv_percent')
         or coalesce(l_h6, '~') != 'net_contents'
         or coalesce(l_h7, '~') not in ('producer', 'producer_name_address', 'bottler_producer')
         or coalesce(l_h8, '~') not in ('country', 'country_of_origin')
         or (l_h9 is not null and l_h9 != 'demo_profile') then
        raise_application_error(
          -20053,
          'Unexpected manifest headers. Use: file_name, application_ref, brand_name, class_type, abv, net_contents, producer, country, demo_profile.'
        );
      end if;

      select count(*)
        into l_manifest_count
        from table(
          apex_data_parser.parse(
            p_content                => p_manifest_blob,
            p_file_name              => p_manifest_file_name,
            p_detect_data_types      => 'N',
            p_force_trim_whitespace  => 'Y',
            -- Count the complete size-limited manifest. Omitting p_max_rows
            -- avoids header/skip off-by-one behavior and lets 301+ rows be rejected.
            p_skip_rows              => 1
          )
        )
       where col001 is not null
          or col002 is not null
          or col003 is not null
          or col004 is not null
          or col005 is not null
          or col006 is not null
          or col007 is not null
          or col008 is not null
          or col009 is not null;

      update alv_batches
         set total_count = l_manifest_count
       where id = p_batch_id;

      if l_manifest_count = 0 then
        raise_application_error(-20043, 'The manifest contains no data rows.');
      elsif l_manifest_count > coalesce(l_max_items, 300) then
        raise_application_error(-20044, 'The manifest exceeds the configured maximum of ' || coalesce(l_max_items, 300) || ' rows.');
      elsif l_mode = 'CONFIGURED'
            and l_provider = 'OPENAI'
            and l_manifest_count > coalesce(l_live_limit, 25) then
        raise_application_error(
          -20045,
          'Live synchronous batches are capped at ' || coalesce(l_live_limit, 25) ||
          ' items in this prototype. Use a demo mode or implement queued workers for production.'
        );
      end if;

      l_zip_entries := apex_zip.get_dir_entries(p_zipped_blob => p_zip_blob);
      if l_zip_entries.count = 0 then
        raise_application_error(-20054, 'The ZIP archive contains no files.');
      end if;

      l_zip_key := l_zip_entries.first;
      while l_zip_key is not null loop
        l_uncompressed_total := l_uncompressed_total + coalesce(l_zip_entries(l_zip_key).uncompressed_length, 0);
        if l_uncompressed_total > coalesce(l_max_uncompressed, 314572800) then
          raise_application_error(-20055, 'The ZIP archive exceeds the configured uncompressed size limit.');
        elsif mime_from_name(l_zip_entries(l_zip_key).file_name) != 'application/octet-stream'
              and l_zip_entries(l_zip_key).uncompressed_length > coalesce(l_max_file, 10485760) then
          raise_application_error(-20056, 'A label image in the ZIP exceeds the configured per-file size limit.');
        end if;
        l_zip_key := l_zip_entries.next(l_zip_key);
      end loop;

      for r in (
        select col001 as file_name,
               col002 as application_ref,
               col003 as brand_name,
               col004 as class_type,
               col005 as abv,
               col006 as net_contents,
               col007 as producer,
               col008 as country,
               col009 as demo_profile
          from table(
            apex_data_parser.parse(
              p_content                => p_manifest_blob,
              p_file_name              => p_manifest_file_name,
              p_detect_data_types      => 'N',
              p_force_trim_whitespace  => 'Y',
              -- The validated manifest is processed without a second row cap,
              -- so all rows (including row 300) are emitted exactly once.
              p_skip_rows              => 1
            )
          )
         where col001 is not null
            or col002 is not null
            or col003 is not null
            or col004 is not null
            or col005 is not null
            or col006 is not null
            or col007 is not null
            or col008 is not null
            or col009 is not null
         order by line_number
      ) loop
        l_row_number := l_row_number + 1;
        l_zip_entry := null;
        l_image_blob := null;
        l_lookup_error := null;
        l_match_count := 0;
        l_abv := safe_number(r.abv);

        -- Prefer an exact archive path. If the manifest uses only a base name,
        -- accept it only when that base name is unique within the archive.
        l_zip_key := l_zip_entries.first;
        while l_zip_key is not null loop
          if lower(replace(l_zip_entries(l_zip_key).file_name, chr(92), '/')) =
             lower(replace(trim(r.file_name), chr(92), '/')) then
            l_zip_entry := l_zip_key;
            exit;
          end if;
          l_zip_key := l_zip_entries.next(l_zip_key);
        end loop;

        if l_zip_entry is null then
          l_zip_key := l_zip_entries.first;
          while l_zip_key is not null loop
            if lower(file_basename(l_zip_entries(l_zip_key).file_name)) =
               lower(file_basename(trim(r.file_name))) then
              l_match_count := l_match_count + 1;
              l_zip_entry := l_zip_key;
            end if;
            l_zip_key := l_zip_entries.next(l_zip_key);
          end loop;

          if l_match_count > 1 then
            l_lookup_error := 'Multiple ZIP entries share the base name "' ||
                              file_basename(trim(r.file_name)) ||
                              '". Put the full archive path in file_name.';
            l_zip_entry := null;
          end if;
        end if;

        if l_zip_entry is not null then
          l_image_blob := apex_zip.get_file_content(
            p_zipped_blob => p_zip_blob,
            p_dir_entry   => l_zip_entries(l_zip_entry)
          );
        end if;

        l_mime_type := mime_from_name(r.file_name);

        if l_mode = 'CONFIGURED' then
          l_demo_profile := null;
        elsif l_mode = 'DEMO_MIXED' then
          l_demo_profile := case mod(l_row_number - 1, 5)
            when 0 then 'PASS'
            when 1 then 'BRAND_MISMATCH'
            when 2 then 'WARNING_ERROR'
            when 3 then 'LOW_CONFIDENCE'
            else 'MISSING_ABV'
          end;
        else
          l_demo_profile := l_mode;
        end if;

        begin
          if l_lookup_error is not null then
            raise_application_error(-20057, l_lookup_error);
          elsif l_zip_entry is null then
            raise_application_error(-20046, 'No image in the ZIP matches manifest file_name "' || trim(r.file_name) || '".');
          end if;

          verify_label(
            p_file_name              => r.file_name,
            p_mime_type              => l_mime_type,
            p_image_blob             => l_image_blob,
            p_application_ref        => r.application_ref,
            p_expected_brand_name    => r.brand_name,
            p_expected_class_type    => r.class_type,
            p_expected_abv           => l_abv,
            p_expected_net_contents  => r.net_contents,
            p_expected_producer      => r.producer,
            p_expected_country       => r.country,
            p_demo_profile           => l_demo_profile,
            p_batch_id               => p_batch_id,
            p_verification_id        => l_verification_id
          );
        exception
          when others then
            l_error_message := substr(sqlerrm, 1, 4000);
            insert_batch_error(
              p_batch_id,
              r.application_ref,
              r.file_name,
              r.brand_name,
              r.class_type,
              l_abv,
              r.net_contents,
              r.producer,
              r.country,
              l_error_message
            );
        end;

        if l_image_blob is not null and dbms_lob.istemporary(l_image_blob) = 1 then
          dbms_lob.freetemporary(l_image_blob);
        end if;
        l_image_blob := null;
      end loop;

      select count(*),
             sum(case when overall_status = 'PASS' then 1 else 0 end),
             sum(case when overall_status = 'FAIL' then 1 else 0 end),
             sum(case when overall_status = 'REVIEW' then 1 else 0 end)
        into l_processed, l_pass, l_fail, l_review
        from alv_verifications
       where batch_id = p_batch_id;

      l_elapsed_ms := round((dbms_utility.get_time - l_start) * 10);

      update alv_batches
         set status = 'COMPLETED',
             processed_count = coalesce(l_processed, 0),
             pass_count = coalesce(l_pass, 0),
             fail_count = coalesce(l_fail, 0),
             review_count = coalesce(l_review, 0),
             processing_ms = l_elapsed_ms,
             completed_at = systimestamp,
             notes = case
               when l_mode = 'CONFIGURED' and l_provider = 'OPENAI'
                 then 'Processed synchronously with the configured live provider.'
               else 'Processed synchronously in deterministic demo mode.'
             end
       where id = p_batch_id;
    exception
      when others then
        l_error_message := substr(sqlerrm, 1, 4000);
        if l_image_blob is not null and dbms_lob.istemporary(l_image_blob) = 1 then
          dbms_lob.freetemporary(l_image_blob);
        end if;
        l_image_blob := null;
        l_elapsed_ms := round((dbms_utility.get_time - l_start) * 10);
        select count(*),
               sum(case when overall_status = 'PASS' then 1 else 0 end),
               sum(case when overall_status = 'FAIL' then 1 else 0 end),
               sum(case when overall_status = 'REVIEW' then 1 else 0 end)
          into l_processed, l_pass, l_fail, l_review
          from alv_verifications
         where batch_id = p_batch_id;

        update alv_batches
           set status = 'FAILED',
               processed_count = coalesce(l_processed, 0),
               pass_count = coalesce(l_pass, 0),
               fail_count = coalesce(l_fail, 0),
               review_count = coalesce(l_review, 0),
               processing_ms = l_elapsed_ms,
               completed_at = systimestamp,
               notes = l_error_message
         where id = p_batch_id;

        -- Propagate fatal batch errors so APEX displays an error rather than a
        -- misleading success notification. Row-level problems remain isolated
        -- and are represented as REVIEW records by insert_batch_error.
        raise;
    end;
  end process_batch;

end alv_verification_pkg;
/


declare
  l_error_count number;
  l_first_error varchar2(4000);
begin
  select count(*)
    into l_error_count
    from user_errors
   where name = 'ALV_VERIFICATION_PKG'
     and type in ('PACKAGE', 'PACKAGE BODY');

  if l_error_count > 0 then
    select object_type || ' line ' || line || ', position ' || position || ': ' || text
      into l_first_error
      from (
        select type as object_type, line, position, text
          from user_errors
         where name = 'ALV_VERIFICATION_PKG'
           and type in ('PACKAGE', 'PACKAGE BODY')
         order by sequence
      )
     where rownum = 1;

    raise_application_error(
      -20099,
      'ALV_VERIFICATION_PKG has ' || l_error_count ||
      ' compilation error(s). First error: ' || substr(l_first_error, 1, 3500)
    );
  end if;
end;
/
